stages:
  - build
  - baseline
  - cleanup

build-jiva:
   stage: build
   before_script:
     - export COMMIT=${CI_COMMIT_SHA:0:8}
     - sudo apt-get install -y
     - sudo apt-get install -y curl open-iscsi
     - export GOPATH=$HOME/go
     - export PATH=$HOME/go/bin:$PATH
     - mkdir -p $HOME/go/src/github.com/openebs/maya
     - rsync -az --delete ${CI_PROJECT_DIR}/ ${HOME}/go/src/github.com/openebs/jiva/ #CI_PROJECT_DIR is full path where project is cloned
     - cd ${HOME}/go/src/github.com/openebs/jiva
   script: 
    - echo "Building-Jiva"
    - echo $COMMIT
    - make build
baseline-image:
  stage: baseline
  script:
     - pwd
     - export BRANCH=${CI_COMMIT_REF_NAME}
     - echo $BRANCH
     - export COMMIT=${CI_COMMIT_SHA:0:7}
     - echo $COMMIT
     - git clone https://github.com/openebs/e2e-infrastructure.git
     - cd e2e-infrastructure/baseline
     - ansible-playbook commit-writer.yml --extra-vars "branch=$BRANCH repo=$CI_PROJECT_NAME commit=$COMMIT"
     - git status
     - git add baseline
     - git status
     - git commit -m "updated $CI_PROJECT_NAME commit:$COMMIT"
     - git push  https://$user:$pass@github.com/openebs/e2e-infrastructure.git --all
     - cat baseline
     - echo "##############################################################################################"
     - echo "JIVA-IMAGE Pushed to DOCKER is $COMMIT"
     - echo "##############################################################################################"
     - echo "###############################################################################################" 
     - echo "Started E2E-PIPELINE"
     - echo "###############################################################################################"
     - curl -X POST -F token=$AWS -F  "variables[TRIGGER]=true"  -F ref=master https://gitlab.openebs.ci/api/v4/projects/7/trigger/pipeline
     - curl -X POST -F token=$AWS -F ref=infra-chaos https://gitlab.openebs.ci/api/v4/projects/7/trigger/pipeline
     - curl -X POST -F token=$GCP -F ref=master https://gitlab.openebs.ci/api/v4/projects/9/trigger/pipeline
     - curl -X POST -F token=$AZURE -F ref=master https://gitlab.openebs.ci/api/v4/projects/20/trigger/pipeline
     - curl -X POST -F token=$PACKET -F ref=master https://gitlab.openebs.ci/api/v4/projects/19/trigger/pipeline
     - curl -X POST -F token=$EKS -F ref=master https://gitlab.openebs.ci/api/v4/projects/27/trigger/pipeline
     - curl -X POST -F token=$GKE -F ref=master https://gitlab.openebs.ci/api/v4/projects/24/trigger/pipeline 

cleanup:
  when: always
  stage: cleanup
  script:
     - sudo rm -r ~/go
     - sudo docker images 
     - sudo docker image prune -a
