stages:
  - build
  - baseline
  - cleanup

build-jiva:
   stage: build
   before_script:
     - export COMMIT=${CI_COMMIT_SHA:0:7}
     - sudo apt-get install -y
     - sudo apt-get install -y curl open-iscsi
     - export GOPATH=$HOME/go
     - export PATH=$HOME/go/bin:$PATH
     - mkdir -p $HOME/go/src/github.com/openebs/maya
     - rsync -az --delete ${CI_PROJECT_DIR}/ ${HOME}/go/src/github.com/openebs/jiva/ #CI_PROJECT_DIR is full path where project is cloned
     - cd ${HOME}/go/src/github.com/openebs/jiva
   script: 
    - echo "Building-Jiva"
    - echo $COMMIT
    - make build_gitlab
baseline-image: 
  stage: baseline
  script:
     - pwd
     - export BRANCH=${CI_COMMIT_REF_NAME}
     - echo $BRANCH
     - export COMMIT=${CI_COMMIT_SHA:0:7}
     - echo $COMMIT
     - git clone https://github.com/$BASELINE_REPO/e2e-infrastructure.git
     - git checkout $BRANCH
     - cd e2e-infrastructure/baseline
     - ansible-playbook commit-writer.yml --extra-vars "branch=$BRANCH repo=$CI_PROJECT_NAME commit=$COMMIT"
     - git status
     - git add baseline
     - git status
     - git commit -m "updated $CI_PROJECT_NAME commit:$COMMIT"
     - git push  https://$user:$pass@github.com/$BASELINE_REPO/e2e-infrastructure.git --all
     - cat baseline
     - echo "##############################################################################################"
     - echo "JIVA-IMAGE Pushed to DOCKER is $COMMIT"
     - echo "##############################################################################################"
     - echo "###############################################################################################" 
     - echo "Started E2E-PIPELINE"
     - echo "###############################################################################################"
     - curl -X POST -F variables[INFRA_BRANCH]=$BRANCH -F token=$OPENSHIFT -F ref=openebsbase https://gitlab.openebs.ci/api/v4/projects/15/trigger/pipeline

cleanup:
  when: always
  stage: cleanup
  script:
     - sudo rm -r ~/go
     - sudo docker images 
     - sudo docker image prune -a --force
