language: go
dist: xenial
sudo: required
install: true
services:
  - docker
go:
  - 1.13.x
env:
  global:
    - GOARCH=$(go env GOARCH)
    - GO_FOR_RELEASE=1.13

jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - RUN_FEATURE_TESTS=1
        - RUN_RESILIENCY_TESTS=0
        - RUN_E2E_AND_FUNCTIONAL_TESTS=0
    - os: linux
      arch: amd64
      env:
        - RUN_FEATURE_TESTS=0
        - RUN_RESILIENCY_TESTS=1
        - RUN_E2E_AND_FUNCTIONAL_TESTS=0
    - os: linux
      arch: amd64
      env:
        - RUN_FEATURE_TESTS=0
        - RUN_RESILIENCY_TESTS=0
        - RUN_E2E_AND_FUNCTIONAL_TESTS=1
    - os: linux
      arch: arm64
    - os: linux
      arch: ppc64le

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y curl open-iscsi
  - go get -u golang.org/x/lint/golint
  - go env && pwd
  - mkdir -p $HOME/gopath/bin

script:
  - make build

  - if [ $RUN_FEATURE_TESTS = 1 ]; then
      make test_features;
    fi
  - if [ $RUN_RESILIENCY_TESTS = 1 ]; then
      make test_resiliency;
    fi
  - if [ $RUN_E2E_AND_FUNCTIONAL_TESTS = 1 ]; then
      sudo docker network create --subnet=172.18.0.0/16 stg-net;
      make test_functional;
    fi

after_success:
  - make _push_image

notifications:
  email:
    recipients:
      - kiran.mova@mayadata.io
      - utkarsh.tripathi@mayadata.io
      - vitta@mayadata.io
      - payes.anand@mayadata.io
